//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp11
{
    using System;
    using System.Collections.Generic;
    
    public partial class access
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public access()
        {
            this.staff = new HashSet<staff>();
        }
    
        public int AccessID { get; set; }
        public string AccessName { get; set; }
        public Nullable<sbyte> AddAccount { get; set; }
        public Nullable<sbyte> RemoveAccount { get; set; }
        public Nullable<sbyte> ModifyAccount { get; set; }
        public Nullable<sbyte> AddProduct { get; set; }
        public Nullable<sbyte> RemoveProduct { get; set; }
        public Nullable<sbyte> ModifyProduct { get; set; }
        public Nullable<sbyte> AddStaff { get; set; }
        public Nullable<sbyte> RemoveStaff { get; set; }
        public Nullable<sbyte> ModifyStaff { get; set; }
        public Nullable<sbyte> DetailStaff { get; set; }
        public Nullable<sbyte> Payment { get; set; }
        public Nullable<sbyte> EditOrder { get; set; }
        public Nullable<sbyte> CancelOrder { get; set; }
        public Nullable<sbyte> RestockIndex { get; set; }
        public Nullable<sbyte> RestockFromWarehouse { get; set; }
        public Nullable<sbyte> CofirmSalesRestock { get; set; }
        public Nullable<sbyte> SetDangerLevelsSales { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<staff> staff { get; set; }
    }
}
