//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp11
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sdpEntities1 : DbContext
    {
        public sdpEntities1()
            : base("name=sdpEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<access> access { get; set; }
        public virtual DbSet<account> account { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<delivery> delivery { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<installation> installation { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<productlist> productlist { get; set; }
        public virtual DbSet<receipt> receipt { get; set; }
        public virtual DbSet<restockretailproduct> restockretailproduct { get; set; }
        public virtual DbSet<restockwarehousestock> restockwarehousestock { get; set; }
        public virtual DbSet<retailstore> retailstore { get; set; }
        public virtual DbSet<retailstorestock> retailstorestock { get; set; }
        public virtual DbSet<staff> staff { get; set; }
        public virtual DbSet<supplier> supplier { get; set; }
        public virtual DbSet<titles> titles { get; set; }
        public virtual DbSet<warehouse> warehouse { get; set; }
        public virtual DbSet<warehousestock> warehousestock { get; set; }
    }
}
