//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp11
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.receipt = new HashSet<receipt>();
        }
    
        public int orderID { get; set; }
        public int customerID { get; set; }
        public Nullable<int> deliveryID { get; set; }
        public Nullable<int> installationID { get; set; }
        public string method { get; set; }
        public double totalPrice { get; set; }
        public System.DateTime payDate { get; set; }
        public string dMethod { get; set; }
        public string deposit { get; set; }
        public string Cancel { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual delivery delivery { get; set; }
        public virtual installation installation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<receipt> receipt { get; set; }
    }
}
