//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp11
{
    using System;
    using System.Collections.Generic;
    
    public partial class restockwarehousestock
    {
        public int warehouseID { get; set; }
        public int supplierID { get; set; }
        public int productID { get; set; }
        public int qty { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual productlist productlist { get; set; }
        public virtual supplier supplier { get; set; }
        public virtual warehouse warehouse { get; set; }
    }
}
