//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp11
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public staff()
        {
            this.delivery = new HashSet<delivery>();
            this.installation = new HashSet<installation>();
            this.department1 = new HashSet<department>();
        }
    
        public int staffID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public System.DateTime birthDate { get; set; }
        public System.DateTime hireDate { get; set; }
        public string gender { get; set; }
        public int departID { get; set; }
        public int titleID { get; set; }
        public Nullable<int> accessID { get; set; }
    
        public virtual access access { get; set; }
        public virtual account account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<delivery> delivery { get; set; }
        public virtual department department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<installation> installation { get; set; }
        public virtual titles titles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<department> department1 { get; set; }
    }
}
